import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import { Paragraph } from '@prj--personal-portfolio-v2/react-cmp-lib/lib';
import paraCss from '@prj--personal-portfolio-v2/ds-lsg-styles/lib/components/atoms/paragraph.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Personal Portfolio v2</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Paragraph className={[paraCss.paragraph, paraCss['paragraph--base']].join(' ')}>
                    BASE - Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt, nemo.
                </Paragraph>
            </main>
        </>
    );
}
