import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import { Paragraph, Heading } from '@prj--personal-portfolio-v2/react-cmp-lib/lib';
import '@prj--personal-portfolio-v2/ds-lsg-styles/lib/components/atoms/paragraph.css';
import '@prj--personal-portfolio-v2/ds-lsg-styles/lib/components/atoms/heading.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Personal Portfolio v2</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Heading level={1} title="Heading Level 1" align="left" />
                <Paragraph>BASE - Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt, nemo.</Paragraph>
            </main>
        </>
    );
}
